# Default values for terraform-operator.

# controller - vars for deployment and service of the server
controller:
  # controller.enabled -- deploy the terraform-operator controller
  enabled: true

  # controller.replicaCount -- number of replicas
  replicaCount: 1

  image:
    # controller.image.repository -- repo name without the tag
    repository: isaaguilar/terraform-operator
    # controller.image.tag -- tag of the image
    tag: v0.1.2
    # controller.image.pullPolicy --  Set how kubernetes determines when
    # to pull the docker image.
    pullPolicy: Always

  # controller.args -- additional arguments for the command
  # @default -- <a href="values.yaml#L22-L24">values.yaml</a>
  args:
  - --zap-level=debug
  - --zap-encoder=console

  # controller.resources -- CPU/Memory request and limit configuration
  resources: {}
    # limits:
    #   cpu: 50m
    #   memory: 128M
    # requests:
    #   cpu: 25m
    #   memory: 64M

  # controller.environmentVars -- key/value envs
  environmentVars: {}
    # DOCKERREPO: isaaguilar

  # controller.nodeSelector -- node labels for pod assignment
  nodeSelector: {}

  # controller.tolerations -- List of node taints to tolerate
  tolerations: []

  # controller.affinity -- node/pod affinities
  affinity: {}


