apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraform-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: terraform-operator
  template:
    metadata:
      labels:
        name: terraform-operator
    spec:
      serviceAccountName: terraform-operator
      containers:
        - name: terraform-operator
          # Replace this with the built image name
          image: isaaguilar/terraform-operator:0.0.1
          command:
          - terraform-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
              # valueFrom:
              #   fieldRef:
              #     fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "terraform-operator"    

              